[package]
name = "luneweb"
version = "0.1.9"
edition = "2021"

[features]
default = [
    "datetime",
    "fs",
    "luau",
    "net",
    "process",
    "regex",
    "roblox",
    "serde",
    "stdio",
    "task"]

datetime = [ "lune-std/datetime" ]
fs = [ "lune-std/fs" ]
luau = [ "lune-std/luau" ]
net = [ "lune-std/net" ]
process = [ "lune-std/process" ]
regex = [ "lune-std/regex" ]
roblox = [ "lune-std/roblox" ]
serde = [ "lune-std/serde" ]
stdio = [ "lune-std/stdio" ]
task = [ "lune-std/task" ]

# Using a lune-std fork that let's us add our own standard libraries
[dependencies.lune-std]
git = "https://github.com/HighFlowey/luneweb"
branch = "custom-aliases"
package = "lune-std"
default-features = false

[dependencies]
mlua = { version = "0.9.8", features = ["luau"] }
lune-utils = "0.1.0"
lune-std-serde = "0.1.0"
mlua-luau-scheduler = "0.0.2"
serde = "1.0.202"
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["full"] }
once_cell = "1.19.0"
wry = "0.40.0"
tao = "0.28.0"
http = "1.1.0"
bstr = "1.9.1"
