[package]
name = "luneweb"
version = "0.3.0"
edition = "2021"

[dependencies.lune-std]
git = "https://github.com/LuneWeb/Lune"
rev = "96570554fd6bb5ae6f483fea29337822ca10b0c2"
package = "lune-std"

[dependencies.mlua-luau-scheduler]
git = "https://github.com/LuneWeb/Lune"
rev = "96570554fd6bb5ae6f483fea29337822ca10b0c2"
package = "mlua-luau-scheduler"

[dependencies]
mlua = { version = "0.9.9", features = ["luau"] }
tokio = { version = "1.38.0", features = ["full"] }
include_dir = "0.7.4"
wry = "0.41.0"
tao = "0.28.1"

# lune-utils = "0.1.0"
# lune-std-serde = "0.1.0"
# serde = "1.0.202"
# serde_json = "1.0.117"
# http = "1.1.0"
# bstr = "1.9.1"
# once_cell = "1.19.0"
