[package]
name = "luneweb"
version = "0.1.6"
edition = "2021"

# Using a lune-std fork that let's us add our own standard libraries
[dependencies.lune-std]
git = "https://github.com/HighFlowey/luneweb"
branch = "custom-aliases"
package = "lune-std"
features = [
    "task",
    "fs",
    "serde"
]

[dependencies]
mlua = { version = "0.9.8", features = ["luau"] }
lune-utils = "0.1.0"
lune-std-serde = "0.1.0"
mlua-luau-scheduler = "0.0.2"
serde = "1.0.202"
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["full"] }
once_cell = "1.19.0"
wry = "0.39.5"
tao = "0.28.0"
