[package]
name = "luneweb"
version = "0.2.3"
edition = "2021"

[features]
default = ["webview"]
webview = ["dep:wry"]

# Using a lune-std fork that let's us add our own standard libraries
[dependencies.lune-std]
git = "https://github.com/LuneWeb/Lune"
rev = "e1d5448e9ad01a65afe5c702e4ca0af420edd0b3"
package = "lune-std"
default-features = false

[dependencies.mlua-luau-scheduler]
git = "https://github.com/LuneWeb/Lune"
rev = "e1d5448e9ad01a65afe5c702e4ca0af420edd0b3"
package = "mlua-luau-scheduler"

[dependencies]
mlua = { version = "0.9.8", features = ["luau"] }
lune-utils = "0.1.0"
lune-std-serde = "0.1.0"
serde = "1.0.202"
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["full"] }
once_cell = "1.19.0"
wry = { version = "0.40.1", optional = true }
tao = "0.28.0"
http = "1.1.0"
bstr = "1.9.1"
