[package]
name = "luneweb-rs"
version = "1.1.1"
edition = "2021"

[dependencies]
mlua-luau-scheduler = "0.0.2"
tokio = { version = "1.38.0", features = ["full"] }
mlua = { version = "0.9.9", features = ["luau", "async"] }
wry = { version = "0.42.0", features = ["devtools"] }
tao = "0.28.1"
