name = "luneweb/dom"
version = "0.2.0"
description = "bindings for interacting with the DOM"
repository = "https://github.com/LuneWeb/LuneWeb"
license = "MIT"
includes = ["pesde.toml", "**/*.luau", "**/*.luaurc"]

[target]
environment = "lune"
lib = "init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
