name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install build tooling (x86_64-unknown-linux-gnu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y libwebkit2gtk-4.1-dev
        sudo apt install libgtk-3-dev
    
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    # - name: Run tests
      # run: cargo test --verbose
